### ISSUE TITLE
Uncaught ReferenceError: toggleOpen is not defined

### ISSUE THREAD

**Issue by Supernova3339** [wire-elements/spotlight#126]
```
at [Alpine] toggleOpen() (eval at safeAsyncFunction (module.esm.js:587:19), <anonymous>:3:16)
    at module.esm.js:612:21
    at tryCatch (module.esm.js:527:12)
    at module.esm.js:3271:5
    at handler4 (module.esm.js:2576:25)
    at module.esm.js:2641:5
    at module.esm.js:2578:52
    at Function.dispatch (module.esm.js:90:6)
    at [Alpine] $dispatch('toggle-spotlight') (eval at safeAsyncFunction (module.esm.js:587:19), <anonymous>:3:32)
    at module.esm.js:612:21
    
   ```
   ### Question
<p>
    Hey 👋 <br>
    Any ideas on how to fix this? It occurs when trying to open the Spotlight manually, eg <b>wire:click="toggleSpotlight"</b>
</p>

**Comment by dormeljon** [comment]
same here

**Comment by brianclogan** [comment]
Are you attempting to use a button to open spotlight?
